# Generated by Django 3.0.5 on 2021-05-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=200)),
                ('hash', models.TextField()),
                ('salt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_id', models.CharField(default='', max_length=200)),
                ('advisor_name', models.CharField(default='', max_length=200)),
                ('advisor_pic', models.CharField(default='', max_length=200)),
                ('time', models.DateTimeField()),
                ('user_id', models.CharField()),
            ],
        ),
    ]
